apiVersion: apps/v1
kind: Deployment
metadata:
  name: monappyas
spec:
  replicas: 2
  selector:
    matchLabels:
      app: monappyas
  template:
    metadata:
      labels:
        app: monappyas
    spec:
      containers:
        - name: monappyas
          image: nginx
          ports:
            - containerPort: 80