apiVersion: v1
kind: Pod
metadata:
  name: monappyas-pvc-pod
spec:
  containers:
    - name: monappyas
      image: nginx
      volumeMounts:
        - mountPath: "/data"
          name: monappyas-storage
  volumes:
    - name: monappyas-storage
      persistentVolumeClaim:
        claimName: monappyas-pvc